// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

import (
	"github.com/swanchain/go-computing-provider/internal/db"
)

// Injectors from wire.go:

func NewJob() Job {
	gormDB := db.NewDbService()
	job := Job{
		DB: gormDB,
	}
	return job
}

func NewTask() Task {
	gormDB := db.NewDbService()
	task := Task{
		DB: gormDB,
	}
	return task
}

func NewProvider() Provider {
	gormDB := db.NewDbService()
	provider := Provider{
		DB: gormDB,
	}
	return provider
}
